name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter Manually
        run: |
          # Flutter manually install karen
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter --version
          
      - name: Install Dependencies
        run: flutter pub get
          
      - name: Build APK
        run: flutter build apk --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: islamic-azan-clock
          path: build/app/outputs/flutter-apk/app-release.apk
