name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:$GITHUB_WORKSPACE/flutter/bin"
          flutter --version
          
      - name: Fix Dependencies
        run: |
          # Agar audioplayers version issue ho to fix karen
          sed -i 's/audioplayers: \^6\.0\.0/audioplayers: ^5.2.1/g' pubspec.yaml
          
      - name: Install Dependencies
        run: flutter pub get
          
      - name: Build APK
        run: flutter build apk --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: islamic-azan-clock
          path: build/app/outputs/flutter-apk/app-release.apk
