name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter and Build
        run: |
          # Flutter setup
          wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.9-stable.tar.xz
          tar xf flutter_linux_3.16.9-stable.tar.xz
          
          # Export PATH
          export PATH="$PATH:$GITHUB_WORKSPACE/flutter/bin"
          
          # Verify
          flutter --version
          
          # Build
          flutter pub get
          flutter build apk --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: azan-clock-app
          path: build/app/outputs/flutter-apk/app-release.apk
